version: '3.9'

services:

  nginx:

     image: nginx:1.20-alpine

     ports:

       - "80:80"

     volumes:
       - nginx-data:/etc/nginx/conf.d
       - ./code:/usr/share/nginx/html

volumes:
  nginx-data:
